joint_trajectory:
  - positions: [0.0, 0.5, 0.0, 0.0, 0.0, 0.0]
    velocities: [0.0, 0.1, 0.0, 0.0, 0.0, 0.0]
    time_from_start: 1.0
  - positions: [0.0, 10.0, 0.0, 0.0, 0.0, 0.0]
    velocities: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start: 5.0
